modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Bawnorton/${mod_name}/issues"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "Bawnorton"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"